name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Configure gcloud CLI
        run: |
          gcloud config set project ${{ vars.GCP_PROJECT_ID }}
          gcloud config set run/region us-central1

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          gcloud builds submit --quiet --tag gcr.io/${{ vars.GCP_PROJECT_ID }}/top-games-api:$IMAGE_TAG || exit 1
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Wait for image to be available
        run: |
          for i in {1..30}; do
            if gcloud container images describe gcr.io/${{ vars.GCP_PROJECT_ID }}/top-games-api:$IMAGE_TAG >/dev/null 2>&1; then
              echo "Image found!"
              exit 0
            fi
            echo "Waiting for image... attempt $i"
            sleep 10
          done
          echo "Image not found after timeout"
          exit 1

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy top-games-api \
            --image gcr.io/${{ vars.GCP_PROJECT_ID }}/top-games-api:$IMAGE_TAG \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 8080 \
            --set-env-vars "STEAM_API_KEY=${{ secrets.STEAM_API_KEY }}"